# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.cache/wt [current_project]
set_property parent.project_path C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  {C:/Users/leler/Desktop/EE2026 project/bonus.mem}
  {C:/Users/leler/Desktop/EE2026 project/thank_you.mem}
  {C:/Users/leler/Desktop/EE2026 project/tord.mem}
  {C:/Users/leler/Desktop/EE2026 project/Mario.mem}
  {C:/Users/leler/Desktop/EE2026 project/forest.mem}
  {C:/Users/leler/Desktop/EE2026 project/monster.mem}
  {C:/Users/leler/Desktop/EE2026 project/welcome.mem}
  {C:/Users/leler/Desktop/EE2026 project/got_moon.mem}
  {C:/Users/leler/Desktop/EE2026 project/menu.mem}
  {C:/Users/leler/Desktop/EE2026 project/btnD_hint.mem}
  {C:/Users/leler/Desktop/EE2026 project/oled_background.mem}
  {C:/Users/leler/Desktop/EE2026 project/boarder.mem}
  {C:/Users/leler/Desktop/EE2026 project/door.mem}
  {C:/Users/leler/Desktop/EE2026 project/short_mario.mem}
  {C:/Users/leler/Desktop/EE2026 project/xhint.mem}
  {C:/Users/leler/Desktop/EE2026 project/concert_hint.mem}
  {C:/Users/leler/Desktop/EE2026 project/concert.mem}
  {C:/Users/leler/Desktop/EE2026 project/no_moon.mem}
  {C:/Users/leler/Desktop/EE2026 project/pipe.mem}
  {C:/Users/leler/Desktop/EE2026 project/xian.mem}
  {C:/Users/leler/Desktop/EE2026 project/moon.mem}
  {C:/Users/leler/Desktop/EE2026 project/bg2.mem}
}
read_verilog -library xil_defaultlib {
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Audio_Capture.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Game1_forest.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Game2_concert.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Game3_xian.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Oled_Display.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/clcock_divider.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/concert_render.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/convert_index.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/digit_display_new_version.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/flexible_clock.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/forest_render.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/intensity_new.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/led_display_new.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/mario_game.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/moving_control.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/mux_new.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/my_clock_divider_audio.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/my_dff.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/random.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/random_num.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_bg2.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_btnD_hint.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_concert.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_concert_hint.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_congras.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_door.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_forest_background.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_got_moon.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_mario.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_menu.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_monster.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_moon.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_no_moon.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_oled_background.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_pipe.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_thank_you.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_tord.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_welcome.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_xian_background.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_xian_bonus.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/read_xian_hint.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/render.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/show_menu.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/show_vol_bar.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/single_pulse_circuit.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/snake.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/snake_oled.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/snake_score_display.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/snake_seg_display.v
  C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Top_Student.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/constrs_1/new/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/leler/Desktop/SoundDisplay_new.xpr/SoundDisplay/SoundDisplay.srcs/constrs_1/new/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
